"""Generator for always-on per-script Windows service wrappers.

Generates a PowerShell install script that uses NSSM to wrap a specific
Python script as a Windows service.  The wrapper script also periodically
POSTs a heartbeat to the ScriptManager API.
"""
from __future__ import annotations

import textwrap
from pathlib import Path


_WRAPPER_TEMPLATE = '''\
"""
Always-on wrapper for: {script_path}
Generated by ScriptManager. Edit heartbeat_url / interval if needed.
"""
import sys
import time
import subprocess
import threading
import urllib.request, json

SCRIPT = r"{script_path}"
INTERPRETER = r"{interpreter}"
HEARTBEAT_URL = "{heartbeat_url}"
HEARTBEAT_INTERVAL = {heartbeat_interval}
SERVICE_NAME = "{service_name}"


def _heartbeat():
    while True:
        try:
            payload = json.dumps({{"service_name": SERVICE_NAME, "status": "running"}}).encode()
            req = urllib.request.Request(
                HEARTBEAT_URL, data=payload,
                headers={{"Content-Type": "application/json"}}, method="POST",
            )
            urllib.request.urlopen(req, timeout=5)
        except Exception:
            pass
        time.sleep(HEARTBEAT_INTERVAL)


threading.Thread(target=_heartbeat, daemon=True).start()

while True:
    result = subprocess.run([INTERPRETER, SCRIPT] + sys.argv[1:])
    if result.returncode != 0:
        time.sleep(5)  # brief back-off on failure before restarting
'''


_NSSM_INSTALLER_TEMPLATE = '''\
# Generated by ScriptManager — run as Administrator
$nssm    = "{nssm_path}"
$python  = "{python_path}"
$wrapper = "{wrapper_path}"
$name    = "{service_name}"
$logDir  = "{log_dir}"

New-Item -ItemType Directory -Force -Path $logDir | Out-Null

& $nssm install $name $python $wrapper
& $nssm set $name DisplayName    "ScriptManager: $name"
& $nssm set $name Description    "Always-on script service managed by ScriptManager"
& $nssm set $name AppDirectory   (Split-Path $wrapper)
& $nssm set $name AppStdout      "$logDir\\$name-stdout.log"
& $nssm set $name AppStderr      "$logDir\\$name-stderr.log"
& $nssm set $name AppRotateFiles 1
& $nssm set $name AppRotateBytes 10485760
& $nssm set $name Start          SERVICE_AUTO_START
& $nssm start $name

Write-Host "Service \'$name\' installed and started." -ForegroundColor Green
'''


def generate_always_on_service(
    *,
    service_name: str,
    script_path: str,
    interpreter: str = "python",
    heartbeat_url: str = "http://localhost:8765/api/services/heartbeat",
    heartbeat_interval: int = 60,
    output_dir: str = ".",
    nssm_path: str = "nssm",
    log_dir: str = r"C:\ProgramData\ScriptManager\logs",
) -> dict[str, str]:
    """
    Generate wrapper.py and install.ps1 for the always-on service.
    Returns a dict of {filename: content}.
    """
    import sys

    wrapper_content = _WRAPPER_TEMPLATE.format(
        script_path=script_path,
        interpreter=interpreter,
        heartbeat_url=heartbeat_url,
        heartbeat_interval=heartbeat_interval,
        service_name=service_name,
    )
    wrapper_filename = f"{service_name}_wrapper.py"
    wrapper_path = str(Path(output_dir) / wrapper_filename)

    installer_content = _NSSM_INSTALLER_TEMPLATE.format(
        nssm_path=nssm_path,
        python_path=sys.executable,
        wrapper_path=wrapper_path,
        service_name=service_name,
        log_dir=log_dir,
    )
    installer_filename = f"install_{service_name}.ps1"

    return {
        wrapper_filename: wrapper_content,
        installer_filename: installer_content,
    }
